/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('coach_applications').del();
  await knex('student_applications').del();
  await knex('admins').del();

  const coachData = [
      { 
          id: 1, 
          first_name: 'Coach',
          last_name: '1',
          email: 'coach.1@example.com',
          province: 'Ontario',
          city: 'Toronto',
          address: '123 Main St',
          postal_code: 'M5V1K4',
          date_of_birth: '1985-05-20',
          pronoun: 'He/Him',
          years_of_experience: 5,
          resume_url: 'http://example.com/john_resume.pdf',
          self_identification: 'Some self ID info',
          gen_status: 'General Status 1',
          languages: 'English, French',
          institutions: 'University of Toronto',
          availability: 'Mondays, Tuesdays',
          introduction: 'Hello, I am John.',
          reside_in_canada: true,
          post_secondary_exp: true,
          status: 'verified',
          post_secondary_program: 'Software Engineering',
          verification_code: 123456
      },
      { 
        id: 2, 
        first_name: 'Coach',
        last_name: '2',
        email: 'coach.2@example.com',
        province: 'Ontario',
        city: 'Toronto',
        address: '123 Main St',
        postal_code: 'M5V1K4',
        date_of_birth: '1985-05-20',
        pronoun: 'He/Him',
        years_of_experience: 5,
        resume_url: 'http://example.com/john_resume.pdf',
        self_identification: 'Some self ID info',
        gen_status: 'General Status 1',
        languages: 'English, French',
        institutions: 'University of Toronto',
        availability: 'Mondays, Tuesdays',
        introduction: 'Hello, I am John2.',
        reside_in_canada: true,
        post_secondary_exp: true,
        status: 'verified',
        post_secondary_program: 'Software Engineering',
        verification_code: 123456
    },
    { 
      id: 3, 
      first_name: 'Coach',
      last_name: '3',
      email: 'coach.3@example.com',
      province: 'Ontario',
      city: 'Toronto',
      address: '123 Main St',
      postal_code: 'M5V1K4',
      date_of_birth: '1985-05-20',
      pronoun: 'He/Him',
      years_of_experience: 5,
      resume_url: 'http://example.com/john_resume.pdf',
      self_identification: 'Some self ID info',
      gen_status: 'General Status 1',
      languages: 'English, French',
      institutions: 'University of Toronto',
      availability: 'Mondays, Tuesdays',
      introduction: 'Hello, I am John3.',
      reside_in_canada: true,
      post_secondary_exp: true,
      status: 'pending',
      post_secondary_program: 'Software Engineering',
      verification_code: 123456
  }
      
  ];

  const studentData = [
      { 
          id: 1, 
          first_name: 'Student',
          last_name: '1',
          email: 'student.1@example.com',
          province: 'Ontario',
          city: 'Toronto',
          address: '456 King St',
          postal_code: 'M5V2K5',
          date_of_birth: '2000-10-10',
          pronoun: 'She/Her',
          institution_name: 'University of Toronto',
          program_name: 'Computer Science',
          emergency_contact_first_name: 'John',
          emergency_contact_last_name: 'Doe',
          emergency_contact_phone: '416-555-1234',
          emergency_contact_relation: 'Father',
          status: 'matched',
          verification_code: 654321,
          coach_id: 1
      },
      { 
        id: 2, 
        first_name: 'Student',
        last_name: '2',
        email: 'student.2@example.com',
        province: 'Ontario',
        city: 'Toronto',
        address: '456 King St',
        postal_code: 'M5V2K5',
        date_of_birth: '2000-10-10',
        pronoun: 'She/Her',
        institution_name: 'University of Toronto',
        program_name: 'Computer Science',
        emergency_contact_first_name: 'John',
        emergency_contact_last_name: 'Doe',
        emergency_contact_phone: '416-555-1234',
        emergency_contact_relation: 'Father',
        status: 'matched',
        verification_code: 654322,
        coach_id: 1
    },
    { 
        id: 3, 
        first_name: 'Student',
        last_name: '3',
        email: 'student.3@example.com',
        province: 'Ontario',
        city: 'Toronto',
        address: '457 King St',
        postal_code: 'M5V2K6',
        date_of_birth: '2000-10-11',
        pronoun: 'He/Him',
        institution_name: 'University of Toronto',
        program_name: 'Computer Science',
        emergency_contact_first_name: 'Jane',
        emergency_contact_last_name: 'Doe',
        emergency_contact_phone: '416-555-1235',
        emergency_contact_relation: 'Mother',
        status: 'matched',
        verification_code: 654323,
        coach_id: 1
    },
    { 
      id: 4, 
      first_name: 'Student',
      last_name: '4',
      email: 'student.4@example.com',
      province: 'Ontario',
      city: 'Toronto',
      address: '458 King St',
      postal_code: 'M5V2K7',
      date_of_birth: '2001-01-12',
      pronoun: 'He/Him',
      institution_name: 'University of Toronto',
      program_name: 'Computer Science',
      emergency_contact_first_name: 'Jane',
      emergency_contact_last_name: 'Smith',
      emergency_contact_phone: '416-555-1256',
      emergency_contact_relation: 'Mother',
      status: 'matched',
      verification_code: 654324,
      coach_id: 1
  },
  { 
      id: 5, 
      first_name: 'Student',
      last_name: '5',
      email: 'student.5@example.com',
      province: 'Ontario',
      city: 'Toronto',
      address: '459 King St',
      postal_code: 'M5V2K8',
      date_of_birth: '2001-02-13',
      pronoun: 'She/Her',
      institution_name: 'University of Toronto',
      program_name: 'Software Engineering',
      emergency_contact_first_name: 'Michael',
      emergency_contact_last_name: 'Johnson',
      emergency_contact_phone: '416-555-1267',
      emergency_contact_relation: 'Father',
      status: 'matched',
      verification_code: 654325,
      coach_id: 1
  },
  { 
      id: 6, 
      first_name: 'Student',
      last_name: '6',
      email: 'student.6@example.com',
      province: 'Ontario',
      city: 'Toronto',
      address: '460 King St',
      postal_code: 'M5V2K9',
      date_of_birth: '2001-03-14',
      pronoun: 'They/Them',
      institution_name: 'University of Toronto',
      program_name: 'Information Systems',
      emergency_contact_first_name: 'Linda',
      emergency_contact_last_name: 'Martin',
      emergency_contact_phone: '416-555-1278',
      emergency_contact_relation: 'Sister',
      status: 'matched',
      verification_code: 654326,
      coach_id: 1
  },
  { 
      id: 7, 
      first_name: 'Student',
      last_name: '7',
      email: 'student.7@example.com',
      province: 'Ontario',
      city: 'Toronto',
      address: '461 King St',
      postal_code: 'M5V2K0',
      date_of_birth: '2001-04-15',
      pronoun: 'She/Her',
      institution_name: 'University of Toronto',
      program_name: 'Data Science',
      emergency_contact_first_name: 'Robert',
      emergency_contact_last_name: 'Williams',
      emergency_contact_phone: '416-555-1289',
      emergency_contact_relation: 'Brother',
      status: 'matched',
      verification_code: 654327,
      coach_id: 1
  },
  { 
    id: 8, 
    first_name: 'Student',
    last_name: '8',
    email: 'student.8@example.com',
    province: 'Ontario',
    city: 'Toronto',
    address: '462 King St',
    postal_code: 'M5V2L1',
    date_of_birth: '2001-05-16',
    pronoun: 'He/Him',
    institution_name: 'University of Toronto',
    program_name: 'Mechanical Engineering',
    emergency_contact_first_name: 'Nancy',
    emergency_contact_last_name: 'Jackson',
    emergency_contact_phone: '416-555-1290',
    emergency_contact_relation: 'Mother',
    status: 'matched',
    verification_code: 654328,
    coach_id: 1
  },
  { 
    id: 9, 
    first_name: 'Student',
    last_name: '9',
    email: 'student.9@example.com',
    province: 'Ontario',
    city: 'Toronto',
    address: '463 King St',
    postal_code: 'M5V2L2',
    date_of_birth: '2001-06-17',
    pronoun: 'They/Them',
    institution_name: 'University of Toronto',
    program_name: 'Civil Engineering',
    emergency_contact_first_name: 'Christopher',
    emergency_contact_last_name: 'Lee',
    emergency_contact_phone: '416-555-1301',
    emergency_contact_relation: 'Father',
    status: 'matched',
    verification_code: 654329,
    coach_id: 1
  },
  { 
    id: 10, 
    first_name: 'Student',
    last_name: '10',
    email: 'student.10@example.com',
    province: 'Ontario',
    city: 'Toronto',
    address: '465 King St',
    postal_code: 'M5V2K5',
    date_of_birth: '2000-10-18',
    pronoun: 'They/Them',
    institution_name: 'University of Toronto',
    program_name: 'Computer Science',
    emergency_contact_first_name: 'Jamie',
    emergency_contact_last_name: 'Doe',
    emergency_contact_phone: '416-555-1234',
    emergency_contact_relation: 'Sibling',
    status: 'matched',
    verification_code: 654330,
    coach_id: 1
  },
  { 
    id: 11, 
    first_name: 'Student',
    last_name: '11',
    email: 'student.11@example.com',
    province: 'Ontario',
    city: 'Toronto',
    address: '465 King St',
    postal_code: 'M5V2K5',
    date_of_birth: '2000-10-18',
    pronoun: 'They/Them',
    institution_name: 'University of Toronto',
    program_name: 'Computer Science',
    emergency_contact_first_name: 'Jamie',
    emergency_contact_last_name: 'Doe',
    emergency_contact_phone: '416-555-1234',
    emergency_contact_relation: 'Sibling',
    status: 'pending',
    verification_code: 654330,
    coach_id: null
  }    
  ];

  const adminData = [
      {
          id: 1,
          username: 'admin',
          password: '$2a$10$YVrUx7TDcL1.3iCspv3OFuNYebkOBzhzjBeZZYkwluBc5D0vlGWBW'
      }
  ];

  await knex('coach_applications').insert(coachData);
  await knex('student_applications').insert(studentData);
  await knex('admins').insert(adminData);
};
